### ISSUE TITLE
Roadmap for analysis of multipatch experiments

### ISSUE THREAD

**Issue by campagnola** [aiephys/multipatch_analysis#4]
* [x] NWB browser
    * [x] Summary of sweeps with key parameters (clamp mode, holding cmd)
    * [x] Sweep view
    * [x] Matrix view with averaging, filtering, and artifact removal
* [x] Evoked spike detection for VC and IC
* [ ] Test pulse analysis for automated QC - measure input/access resistance, holding potential/current
* [ ] Synaptic event detection and characterization (spontaneous and evoked)
* [ ] Statistical metrics for detecting connectivity
    * [ ] High Pr / low amplitude
    * [ ] Low Pr / high amplitude
* [x] Distance vs connection probability
    * [x] Depends on ACQ4 / MosaicEditor annotation of cell locations
* [x] Connectivity graph visualization
* [x] Synaptic event properties from averaged traces
    * [ ] Exponential deconvolution for analyzing high-frequency inductions
    * [x] Synaptic dynamics characterization from model fitting
* [ ] Automated analysis
* [ ] Database storage for analysis results 
    * [ ] Secondary analyses: connectivity and synaptic properties vs calcium, temperature, and age
